### ISSUE TITLE
PEM.ne4pg2_ne4pg2.F2010-SCREAMv1.pm-cpu_intel fails

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#2406]
ON pm-cpu, with intel, and only with OPT build, we see non-bfb results when changing PE layouts.
Can reproduce with scream repo of June22, but need mods related to Intel compiler in scream repo.
`PEM.ne4pg2_ne4pg2.F2010-SCREAMv1.pm-cpu_intel`

I could make a branch with the changes, but also needs flag cleanup in ekat.

Starting with a crash with ne30 on chrysalis, we worked toward a smaller reproducer
https://github.com/E3SM-Project/scream/issues/2381

**Comment by ndkeen** [comment]
While Andrew B reported that he does not see any fails with PEM on chrysalis, I do see a fail on frontier using cray compiler.

`PEM_P128x1_Ld1.ne30pg2_ne30pg2.F2010-SCREAMv1.frontier-scream-gpu_crayclang-scream`

`/lustre/orion/cli115/proj-shared/noel/e3sm_scratch/maf-jun19/PEM_P128x1_Ld1.ne30pg2_ne30pg2.F2010-SCREAMv1.frontier-scream-gpu_crayclang-scream.r00`

**Comment by ambrad** [comment]
Chrysalis test description here: https://github.com/E3SM-Project/scream/issues/2381#issuecomment-1605076280

**Comment by ambrad** [comment]
So far Crusher does not reproduce any of these. A summary of results so far follows. I will update these as more come in.
```
  PEM_P128x1_Ld1.ne30pg2_ne30pg2.F2010-SCREAMv1.crusher-scream-gpu_crayclang-scream.scream-internal_diagnostics_level (Overall: PASS) details:
  PEM_P16x1_Ld1.ne30pg2_ne30pg2.F2010-SCREAMv1.crusher-scream-gpu_crayclang-scream.scream-internal_diagnostics_level (Overall: PASS) details:
  PEM_P32x1_Ld1.ne30pg2_ne30pg2.F2010-SCREAMv1.crusher-scream-gpu_crayclang-scream.scream-internal_diagnostics_level (Overall: PASS) details:
  PEM_P64x1_Ld1.ne30pg2_ne30pg2.F2010-SCREAMv1.crusher-scream-gpu_crayclang-scream.scream-internal_diagnostics_level (Overall: PEND) details:
  PEM_P128x1_Ld1.ne30pg2_ne30pg2.F2010-SCREAMv1.crusher-scream-gpu_crayclang-scream (Overall: PASS) details:
  PEM_P16x1_Ld1.ne30pg2_ne30pg2.F2010-SCREAMv1.crusher-scream-gpu_crayclang-scream (Overall: PEND) details:
  PEM.ne4pg2_ne4pg2.F2010-SCREAMv1.crusher-scream-gpu_crayclang-scream (Overall: PEND) details:
  PEM.ne4pg2_ne4pg2.F2010-SCREAMv1.crusher-scream-gpu_crayclang-scream.scream-internal_diagnostics_level (Overall: PEND) details:
```
In addition, I'm running repeat testing on `PEM_P16x1_Ld1.ne30pg2_ne30pg2.F2010-SCREAMv1.crusher-scream-gpu_crayclang-scream.scream-internal_diagnostics_level` and so far am at 2 passes.

**Comment by ambrad** [comment]
Currently running this on Frontier and will update this comment with results:
```bash
compiler=crayclang-scream  
machine=frontier-scream-gpu

tests=""
for sfx in "" ".scream-internal_diagnostics_level"; do
    tests+=" PEM.ne4pg2_ne4pg2.F2010-SCREAMv1.${machine}_${compiler}${sfx}"
done
for npe in 16; do
    for sfx in "" ".scream-internal_diagnostics_level"; do
        tests+=" PEM_P${npe}x1_Ld1.ne30pg2_ne30pg2.F2010-SCREAMv1.${machine}_${compiler}.scream-internal_diagnostics_level"
    done
done
echo $tests

$e3sm/cime/scripts/create_test $tests
```

**Comment by ambrad** [comment]
@ndkeen this is very unlikely, but is it possible that the DIFF you saw resulted from the following sequence? 1. Run PEM_D.ne4pg2... 2. The run gets cancelled due to the wallclock limit. 3. Manually change STOP_N in env_run.xml from 5 to 1 or 2. 4. Forget to do the same for the case2 env_run.xml file. 5. ./case.submit. 6. Diff due to different number of days in the two runs.

I ask because so far I'm unable to reproduce the DIFF with PEM_D_Ld2 and similar tests. Yet I suspect it's an F90 opt-level issue in one of the surface components that is the cause. If we were to change our assessment to that _D passes, we could then use the usual opt-level reduction on a bunch of F90 files to solve the diff in practice.

**Comment by ndkeen** [comment]
All of my PEM tests have worked the first time.  And I can reproduce on pm-cpu/intel and fronter/cray

**Comment by ambrad** [comment]
On pm-cpu/intel, have you run with the scream-internal_diagnostics_level testmod to isolate the diff?

**Comment by ambrad** [comment]
Re: the PEM_D fails, I'm seeing this in your test directory:
```
[ambradl@login04.frontier PEM_D.ne4pg2_ne4pg2.F2010-SCREAMv1.frontier-scream-gpu_crayclang-scream.20230623_205834_u7fj79]$ for i in `find . -name env_run.xml`; do echo $i; grep "\"STOP_N" $i; done
./case2/PEM_D.ne4pg2_ne4pg2.F2010-SCREAMv1.frontier-scream-gpu_crayclang-scream.20230623_205834_u7fj79/env_run.xml
    <entry id="STOP_N" value="5">
./env_run.xml
    <entry id="STOP_N" value="1">
```
The two STOP_N values are different. I did the same thing when setting up my repeat testing, which made me think you might have, too.

**Comment by ndkeen** [comment]
On pm-cpu/intel (which again unfortunately is not ready out-of-box, but i could make a branch) I see I did not turn on internal diagnostics with these simply tests, so just started:
```
 PEM_P8x1.ne4pg2_ne4pg2.F2010-SCREAMv1.pm-cpu_intel.scream-internal_diagnostics_level
 PEM_P8x1_Ln6.ne4pg2_ne4pg2.F2010-SCREAMv1.pm-cpu_intel.scream-internal_diagnostics_level
```

And on Frontier, using newer branch, I just started:
```
PEM_P8x1.ne4pg2_ne4pg2.F2010-SCREAMv1.frontier-scream-gpu_crayclang-scream PEM_D_P8x1.ne4pg2_ne4pg2.F2010-SCREAMv1.frontier-scream-gpu_crayclang-scream

and

PEM_D_P8x1.ne4pg2_ne4pg2.F2010-SCREAMv1.frontier-scream-gpu_crayclang-scream.scream-internal_diagnostics_level
PEM_P8x1.ne4pg2_ne4pg2.F2010-SCREAMv1.frontier-scream-gpu_crayclang-scream.scream-internal_diagnostics_level

```

Will update here when they complete

**Comment by ambrad** [comment]
@ndkeen this looks promising: https://github.com/E3SM-Project/scream/commit/68a174902527d3fa831a5d4ccc55d27f6c763cee

If you'd like to put it through its paces on Frontier to confirm what I'm seeing and you find it works, I'll merge the commit into the machines/fronter branch.

You can get this commit by merging ambrad/frontier-cice-O0 into your local machines/frontier branch.

**Comment by ambrad** [comment]
Noel and I think the CICE optimization reduction is promising for Frontier: all of our tests have passed. I've merged the commit into machines/frontier.

**Comment by ambrad** [comment]
Re: /lustre/orion/cli115/proj-shared/noel/e3sm_scratch/maf-jun26/PEM_D_P8x1.ne4pg2_ne4pg2.F2010-SCREAMv1.frontier-scream-gpu_crayclang-scream.scream-internal_diagnostics_level.r00

1. The FAIL is in RUN, not COMPARE:
```
FAIL PEM_D_P8x1.ne4pg2_ne4pg2.F2010-SCREAMv1.frontier-scream-gpu_crayclang-scream.scream-internal_diagnostics_level RUN time=7198
PEND PEM_D_P8x1.ne4pg2_ne4pg2.F2010-SCREAMv1.frontier-scream-gpu_crayclang-scream.scream-internal_diagnostics_level COMPARE_base_modpes
```

2. The hash stream that is available shows the first diff is where the first run was able to go longer than the second:
```
$ zgrep "hash>" ./run/e3sm.log.1363747.230627-164100.gz > r1.txt; zgrep "hash>" ./run/case2run/e3sm.log.1363747.230627-180418 > r2.txt; diff r1.txt r2.txt | head -n 20
40853,98407d40852
< 0: exxhash>    1-  2.04167 0 1af82f2ef5aa3059 (mac_aero_mic-pre-sc-17)
```

3. I conclude that this is not a valid debug-build diff; therefore, we have yet to see a debug-build diff.

**Comment by ndkeen** [comment]
Yep, you're right, I did not look closely enough at the reasons for the fails and the DEBUG PEM tests on frontier are run fails not compare fails.

I can verify that at least one PEM (OPT build) does pass with the reduced opt flag in CICE sources on frontier. But the machine has been down a while and no others tests have run.

On pm-cpu/intel, I still see the compare fail, even with
`PEM_P8x1_Ln6.ne4pg2_ne4pg2.F2010-SCREAMv1.pm-cpu_intel.scream-internal_diagnostics_level`
It does not fail with DEBUG and doe not fail with gnu compiler.
I tried reducing opt on the CICE sources in the way way, no difference.
I then tried reducing compiler opts in general, and I can get a PASS if I change the CXX compiler flag in EKAT for `-O3 to -O0`.

**Comment by ambrad** [comment]
For the pm-cpu run, the hash lines show the diff is in the Hommexx version of SL transport. The hyperviscosity operator sees the diff first because of the boundary exchange pattern, but very likely it occurs in the core SL code and not HV. My thinking right now is this: 1. The priority on running EAMxx on pm-cpu is quite low. 2. This is extremely likely to be a compiler optimization-pass issue, not an actual code bug. Therefore, I'm not going to attempt to resolve it right now.

**Comment by ambrad** [comment]
@ndkeen, one thing you might check is `-fp-model` for the C++ code. In intel_pm-cpu.cmake, I see
```
string(APPEND CXXFLAGS " -fp-model=precise") # and manually add precise                                                                                                                                                                 
...
string(APPEND CXXFLAGS " -fp-model=consistent")
```
That is, it's `precise`, but then a later line passes `consistent`, which I think might partially or fully override `precise`. I don't understand `consistent` very well, but my impression is it's not as safe as `precise` or `source`.

**Comment by ndkeen** [comment]
`-fp-model=consistent` is the most safe.
I can try adjusting flags next.

**Comment by ambrad** [comment]
> -fp-model=consistent is the most safe, but I think is only available for ifort (well the man page indicated ifort only, but icpx accepts it). I can try adjusting flags next.

Ok, if `consistent` is at least as safe or meaningless for ifx, then that can't be it. Have you tried an ifort rather than ifx build?

**Comment by ambrad** [comment]
Oh, I wasn't thinking when I wrote "ifx" above. On pm-cpu, it's the C++ compiler that matters, as all the dycore code is in C++.

**Comment by ndkeen** [comment]
Currently, it looks like many C++ files are being built ignoring flags set via CIME, so I've been editing `externals/ekat/cmake/EkatSetCompilerFlags.cmake` to experiment.

I found that I can get compare PASS if I build with the default `-O3` and then add `-fp-model=precise` to ekat C++ files.

```
      string(APPEND CMAKE_CXX_FLAGS_RELEASE " -O3")
      string(APPEND CMAKE_CXX_FLAGS_RELEASE " -fp-model=precise")
```

**Comment by ndkeen** [comment]
`PEM.ne4pg2_ne4pg2.F2010-SCREAMv1.pm-cpu_intel` still fails compare with checkout of Dec 3
