### ISSUE TITLE
Build-time error (at case.setup) with new SCREAM compsets (with no other changes, out-of-box)

### ISSUE THREAD

**Issue by ndkeen** [E3SM-Project/scream#489]
Using a repo of July 28th (and testing again with repo of Aug 3rd), the scripts I was using to launch ne256 and ne1024 jobs have not been acting the same.  The last repo I used to launch a successful ne256 test was July 15th.

It looks like I need to use either `F2000-SCREAM-HR-DYAMOND1` or `F2010-SCREAM-HR-DYAMOND1` compset, but both seem to fail with my ne256 and ne1024 scripts.
For ne256, I am trying res=`ne256pg2_r0125_oRRS18to6v3` and for ne1024, `ne1024pg2_r0125_oRRS18to6v3`

```
ERROR: Command: '/global/cscratch1/sd/ndk/wacmy/s23-aug3/components/clm/bld/build-namelist -infile /global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/s23-aug3/F2000-SCREAM-HR-DYAMOND1.ne25
6pg2tri.s23-aug3.n0128t64x211121.wr.24s.nc00c.N144/Buildconf/clmconf/namelist  -csmdata /global/cfs/cdirs/e3sm/inputdata -inputdata /global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/s23-a
ug3/F2000-SCREAM-HR-DYAMOND1.ne256pg2tri.s23-aug3.n0128t64x211121.wr.24s.nc00c.N144/Buildconf/clm.input_data_list -ignore_ic_date -namelist " &clm_inparm  start_ymd=20160801  /" -use_c
ase 2000_control  -res r0125  -clm_start_type default -envxml_dir /global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/s23-aug3/F2000-SCREAM-HR-DYAMOND1.ne256pg2tri.s23-aug3.n0128t64x211121.
wr.24s.nc00c.N144 -l_ncpl 144 -lnd_frac /global/cfs/cdirs/e3sm/inputdata/share/domains/domain.lnd.r0125_oRRS18to6v3.200212.nc -glc_nec 0 -co2_ppmv 367.0 -co2_type diagnostic  -config /
global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/s23-aug3/F2000-SCREAM-HR-DYAMOND1.ne256pg2tri.s23-aug3.n0128t64x211121.wr.24s.nc00c.N144/Buildconf/clmconf/config_cache.xml -bgc sp -mask 
oRRS18to6v3' failed with error 'File::Glob::glob() will disappear in perl 5.30. Use File::Glob::bsd_glob() instead. at /global/cscratch1/sd/ndk/wacmy/s23-aug3/components/clm/bld/CLMBui
ldNamelist.pm line 3743.
ERROR : CLM build-namelist::CLMBuildNamelist::add_default() : No default value found for fsurdat.
            Are defaults provided for this resolution and land mask?' from dir '/global/cscratch1/sd/ndk/e3sm_scratch/cori-knl/s23-aug3/F2000-SCREAM-HR-DYAMOND1.ne256pg2tri.s23-aug3.n0
128t64x211121.wr.24s.nc00c.N144/Buildconf/clmconf'
```

I can confirm that the issue is in case.setup.  Easy to repeat:

```
create_newcase --case c --res ne256pg2_r0125_oRRS18to6v3 --compset F2010-SCREAM-HR-DYAMOND1
cd c
case.setup

create_newcase --case c --res ne1024pg2_r0125_oRRS18to6v3 --compset F2010-SCREAM-HR-DYAMOND1
cd c
case.setup

Same in both cases for compset F2000-SCREAM-HR-DYAMOND1
```

Using master, I also seem to get related error, but I'm being told this is a different issue.

```
create_newcase --case c --res ne256pg2_r0125_oRRS18to6v3 --compset FC5AV1C-H01A
cd c
case.setup

Creating component namelists
  2020-08-05 12:33:16 atm 
   Calling /global/cscratch1/sd/ndk/wacmy/m37-jul7/components/cam/cime_config/buildnml
  2020-08-05 12:33:16 lnd 
   Calling /global/cscratch1/sd/ndk/wacmy/m37-jul7/components/clm/cime_config/buildnml
ERROR: Command: '/global/cscratch1/sd/ndk/wacmy/m37-jul7/components/clm/bld/build-namelist -infile /global/cscratch1/sd/ndk/wacmy/m37-jul7/cime/scripts/c/Buildconf/clmconf/namelist  -csmdata /global/cfs/cdirs/e3sm/inputdata -inputdata /global/cscratch1/sd/ndk/wacmy/m37-jul7/cime/scripts/c/Buildconf/clm.input_data_list -ignore_ic_year -namelist " &clm_inparm  start_ymd=00010101  /" -use_case 2000_control  -res r0125  -clm_start_type default -envxml_dir /global/cscratch1/sd/ndk/wacmy/m37-jul7/cime/scripts/c -l_ncpl 48 -lnd_frac /global/cfs/cdirs/e3sm/inputdata/share/domains/domain.lnd.r0125_oRRS18to6v3.200212.nc -glc_nec 0 -co2_ppmv 368.865 -co2_type diagnostic  -config /global/cscratch1/sd/ndk/wacmy/m37-jul7/cime/scripts/c/Buildconf/clmconf/config_cache.xml -bgc sp -mask oRRS18to6v3' failed with error 'File::Glob::glob() will disappear in perl 5.30. Use File::Glob::bsd_glob() instead. at /global/cscratch1/sd/ndk/wacmy/m37-jul7/components/clm/bld/CLMBuildNamelist.pm line 3743.
ERROR : CLM build-namelist::CLMBuildNamelist::add_default() : No default value found for fsurdat.
            Are defaults provided for this resolution and land mask?' from dir '/global/cscratch1/sd/ndk/wacmy/m37-jul7/cime/scripts/c/Buildconf/clmconf'
```

**Comment by ndkeen** [comment]
Just noting that the following command also demonstrates that we have errors at case setup time with current scream:  
```./create_test --no-build SMS_B.ne256pg2_r0125_oRRS18to6v3.F2000-SCREAM-LR SMS_B.ne256pg2_r0125_oRRS18to6v3.F2010-SCREAM-LR SMS_B.ne256pg2_r0125_oRRS18to6v3.F2000-SCREAM-HR SMS_B.ne256pg2_r0125_oRRS18to6v3.F2010-SCREAM-HR```

**Comment by ndkeen** [comment]
With this branch, when I try to do case.setup only (ie no compiling) for a battery of compset/resolution combinations, there are a few FAILs, but perhaps that is fine as the input files are not created. Just reporting all here for completeness.

Results using F20**-SCREAM-LR-DYAMOND1:
```
PASS SMS_B.ne1024pg2_r0125_oRRS18to6v3.F2000-SCREAM-HR-DYAMOND1.cori-knl_intel SETUP
PASS SMS_B.ne1024pg2_r0125_oRRS18to6v3.F2000-SCREAM-LR-DYAMOND1.cori-knl_intel SETUP
PASS SMS_B.ne1024pg2_r0125_oRRS18to6v3.F2010-SCREAM-HR-DYAMOND1.cori-knl_intel SETUP
PASS SMS_B.ne1024pg2_r0125_oRRS18to6v3.F2010-SCREAM-LR-DYAMOND1.cori-knl_intel SETUP

PASS SMS_B.ne512pg2_r0125_oRRS18to6v3.F2000-SCREAM-HR-DYAMOND1.cori-knl_intel SETUP
PASS SMS_B.ne512pg2_r0125_oRRS18to6v3.F2000-SCREAM-LR-DYAMOND1.cori-knl_intel SETUP
PASS SMS_B.ne512pg2_r0125_oRRS18to6v3.F2010-SCREAM-HR-DYAMOND1.cori-knl_intel SETUP
PASS SMS_B.ne512pg2_r0125_oRRS18to6v3.F2010-SCREAM-LR-DYAMOND1.cori-knl_intel SETUP

PASS SMS_B.ne256pg2_r0125_oRRS18to6v3.F2000-SCREAM-HR-DYAMOND1.cori-knl_intel SETUP
PASS SMS_B.ne256pg2_r0125_oRRS18to6v3.F2000-SCREAM-LR-DYAMOND1.cori-knl_intel SETUP
PASS SMS_B.ne256pg2_r0125_oRRS18to6v3.F2010-SCREAM-HR-DYAMOND1.cori-knl_intel SETUP
PASS SMS_B.ne256pg2_r0125_oRRS18to6v3.F2010-SCREAM-LR-DYAMOND1.cori-knl_intel SETUP

FAIL SMS_B.ne120pg2_r0125_oRRS18to6v3.F2000-SCREAM-HR-DYAMOND1.cori-knl_intel (phase SETUP)
PASS SMS_B.ne120pg2_r0125_oRRS18to6v3.F2000-SCREAM-LR-DYAMOND1.cori-knl_intel SETUP
FAIL SMS_B.ne120pg2_r0125_oRRS18to6v3.F2010-SCREAM-HR-DYAMOND1.cori-knl_intel (phase SETUP)
PASS SMS_B.ne120pg2_r0125_oRRS18to6v3.F2010-SCREAM-LR-DYAMOND1.cori-knl_intel SETUP

PASS SMS_B.ne30pg2_ne30pg2.F2000-SCREAM-HR-DYAMOND1.cori-knl_intel SETUP
PASS SMS_B.ne30pg2_ne30pg2.F2000-SCREAM-LR-DYAMOND1.cori-knl_intel SETUP
FAIL SMS_B.ne30pg2_ne30pg2.F2010-SCREAM-HR-DYAMOND1.cori-knl_intel (phase SETUP)
FAIL SMS_B.ne30pg2_ne30pg2.F2010-SCREAM-LR-DYAMOND1.cori-knl_intel (phase SETUP)

PASS SMS_B.ne30pg2_r0125_oRRS18to6v3.F2000-SCREAM-HR-DYAMOND1.cori-knl_intel SETUP
PASS SMS_B.ne30pg2_r0125_oRRS18to6v3.F2000-SCREAM-LR-DYAMOND1.cori-knl_intel SETUP
PASS SMS_B.ne30pg2_r0125_oRRS18to6v3.F2010-SCREAM-HR-DYAMOND1.cori-knl_intel SETUP
PASS SMS_B.ne30pg2_r0125_oRRS18to6v3.F2010-SCREAM-LR-DYAMOND1.cori-knl_intel SETUP

PASS SMS_B.ne4pg2_ne4pg2.F2000-SCREAM-HR-DYAMOND1.cori-knl_intel SETUP
PASS SMS_B.ne4pg2_ne4pg2.F2000-SCREAM-LR-DYAMOND1.cori-knl_intel SETUP
FAIL SMS_B.ne4pg2_ne4pg2.F2010-SCREAM-HR-DYAMOND1.cori-knl_intel (phase SETUP)
FAIL SMS_B.ne4pg2_ne4pg2.F2010-SCREAM-LR-DYAMOND1.cori-knl_intel (phase SETUP)
```

Results using F20**-SCREAM-*R:
```
FAIL SMS_B.ne1024pg2_r0125_oRRS18to6v3.F2000-SCREAM-HR.cori-knl_intel (phase SETUP)
FAIL SMS_B.ne1024pg2_r0125_oRRS18to6v3.F2000-SCREAM-LR.cori-knl_intel (phase SETUP)
FAIL SMS_B.ne1024pg2_r0125_oRRS18to6v3.F2010-SCREAM-HR.cori-knl_intel (phase SETUP)
FAIL SMS_B.ne1024pg2_r0125_oRRS18to6v3.F2010-SCREAM-LR.cori-knl_intel (phase SETUP)

FAIL SMS_B.ne512pg2_r0125_oRRS18to6v3.F2000-SCREAM-HR.cori-knl_intel (phase SETUP)
FAIL SMS_B.ne512pg2_r0125_oRRS18to6v3.F2000-SCREAM-LR.cori-knl_intel (phase SETUP)
FAIL SMS_B.ne512pg2_r0125_oRRS18to6v3.F2010-SCREAM-HR.cori-knl_intel (phase SETUP)
FAIL SMS_B.ne512pg2_r0125_oRRS18to6v3.F2010-SCREAM-LR.cori-knl_intel (phase SETUP)

PASS SMS_B.ne256pg2_r0125_oRRS18to6v3.F2000-SCREAM-HR.cori-knl_intel SETUP
PASS SMS_B.ne256pg2_r0125_oRRS18to6v3.F2000-SCREAM-LR.cori-knl_intel SETUP
PASS SMS_B.ne256pg2_r0125_oRRS18to6v3.F2010-SCREAM-HR.cori-knl_intel SETUP
PASS SMS_B.ne256pg2_r0125_oRRS18to6v3.F2010-SCREAM-LR.cori-knl_intel SETUP

FAIL SMS_B.ne120pg2_r0125_oRRS18to6v3.F2000-SCREAM-HR.cori-knl_intel (phase SETUP)
PASS SMS_B.ne120pg2_r0125_oRRS18to6v3.F2000-SCREAM-LR.cori-knl_intel SETUP
FAIL SMS_B.ne120pg2_r0125_oRRS18to6v3.F2010-SCREAM-HR.cori-knl_intel (phase SETUP)
PASS SMS_B.ne120pg2_r0125_oRRS18to6v3.F2010-SCREAM-LR.cori-knl_intel SETUP

PASS SMS_B.ne30pg2_ne30pg2.F2000-SCREAM-HR.cori-knl_intel SETUP
PASS SMS_B.ne30pg2_ne30pg2.F2000-SCREAM-LR.cori-knl_intel SETUP
FAIL SMS_B.ne30pg2_ne30pg2.F2010-SCREAM-HR.cori-knl_intel (phase SETUP)
FAIL SMS_B.ne30pg2_ne30pg2.F2010-SCREAM-LR.cori-knl_intel (phase SETUP)

PASS SMS_B.ne30pg2_r0125_oRRS18to6v3.F2000-SCREAM-HR.cori-knl_intel SETUP
PASS SMS_B.ne30pg2_r0125_oRRS18to6v3.F2000-SCREAM-LR.cori-knl_intel SETUP
PASS SMS_B.ne30pg2_r0125_oRRS18to6v3.F2010-SCREAM-HR.cori-knl_intel SETUP
PASS SMS_B.ne30pg2_r0125_oRRS18to6v3.F2010-SCREAM-LR.cori-knl_intel SETUP

PASS SMS_B.ne4pg2_ne4pg2.F2000-SCREAM-HR.cori-knl_intel SETUP
PASS SMS_B.ne4pg2_ne4pg2.F2000-SCREAM-LR.cori-knl_intel SETUP
FAIL SMS_B.ne4pg2_ne4pg2.F2010-SCREAM-HR.cori-knl_intel (phase SETUP)
FAIL SMS_B.ne4pg2_ne4pg2.F2010-SCREAM-LR.cori-knl_intel (phase SETUP)
```

**Comment by ndkeen** [comment]
And there is a build error that Ben and I encountered that I now believe is not related to this PR.

We also see this build error (it's at link time) in other situations and what I'm seeing is that for some reason, the build will work if we ask it to use more than one node. So it's somehow dependent on the number of MPI's.  So far, there is not a situation where it doesn't build and we want it to use 1 node -- ie we actually want to use many nodes for these runs anyway. It just doesn't make sense that it would fail at _build_ time.

```
SMS.ne1024pg2_r0125_oRRS18to6v3.F2000-SCREAM-HR-DYAMOND1     

fails to build at link time with errors like:

allreduce.c:(.text+0xb3): relocation truncated to fit: R_X86_64_32S against symbol `MPID_Op_direct' defined in .bss section in /opt/cray/pe/mpt/7.7.10/gni/mpich-intel/16.0/lib/libmpich.a(lib_libmpich_intel_la-op_create.o)

where this works:
SMS_P8192.ne1024pg2_r0125_oRRS18to6v3.F2000-SCREAM-HR-DYAMOND1 
```

So I think we should go forward with this PR.

**Comment by PeterCaldwell** [comment]
I think the original problem documented by this issue was fixed by https://github.com/E3SM-Project/scream/pull/637 . The last comment seems like a different issue, but I don't think we've had problems building for a few months so can close this? @ndkeen or @brhillman - if you agree, could you hit the close button?

**Comment by ndkeen** [comment]
We (Ben) definitely fixed the main issue of not being able to build needed cases. But I didn't close it as there were still a few not-so-important cases that were not building. I'm trying again now. But either way, I think it's OK to close this and open another more specific issue if needed.

**Comment by PeterCaldwell** [comment]
Ok, I think opening a new, more specific issue is the way to go if needed. Thanks! Closing.

**Comment by ndkeen** [comment]
With a new checkout of scream, I still get that same error above trying to do
`create_test SMS.ne1024pg2_r0125_oRRS18to6v3.F2000-SCREAM-HR-DYAMOND1`

I will create another issue just to organize.
